FROM golang:1.12

RUN apt-get update && apt-get install -y --no-install-recommends \
        gettext-base \
    && rm -rf /var/lib/apt/lists/*

ENV YAML_BIN_VERSION 2.2.1
ENV JQ_BIN_VERSION 1.5

RUN wget -O /usr/local/bin/jq "https://github.com/stedolan/jq/releases/download/jq-${JQ_BIN_VERSION}/jq-linux64" \
    && chmod 755 /usr/local/bin/jq \
    && wget -O /usr/local/bin/yaml "https://github.com/mikefarah/yq/releases/download/${YAML_BIN_VERSION}/yq_linux_amd64" \
    && chmod 755 /usr/local/bin/yaml

ENV GO111MODULE=on

RUN go get github.com/golangci/golangci-lint/cmd/golangci-lint \
    && go get golang.org/x/tools/cmd/goimports \
    && go get github.com/mitchellh/gox \
    && go get github.com/davecheney/godoc2md \
    && go get github.com/axw/gocov/gocov \
    && go get github.com/t-yuki/gocov-xml \
    && go get github.com/tebeka/go2xunit \
    && go get github.com/go-swagger/go-swagger/cmd/swagger 

RUN go mod download

RUN CGO_ENABLED=0

ARG DEVELOPER
